name: "Observation plots"
on:
  schedule:
    ### structure: minute, hour, day, month, day of week. Time must be in UTC
    - cron:  '5,35 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Get current date
        id: date
        run: echo "$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Checkout repository
        ### Latest at time of writing
        uses: actions/checkout@v3.3.0
      
      - name: Trigger plot generation via Cloud Run
        run: |
          curl -s -X POST https://obs-plot-service-dfsedjpfbq-uc.a.run.app/trigger-plot-job
